[package]
name = "bevy_arrows_plugin"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.15.3", default-features = false, features = ["bevy_asset", "bevy_pbr"] }

[dev-dependencies]
bevy = "0.15.3"
bevy-inspector-egui = "0.30.0"
bevy_tweening = "0.12.0"
rand = "0.9.0"
